name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup
        run: |
          yarn

      - name: Build
        run: |
          yarn release
        env:
          GH_TOKEN: ${{ secrets.token }}
